### ISSUE TITLE
Error When Looking for "Empty" Movie Folders

### ISSUE THREAD

**Issue by Dreded** [ngovil21/Plex-Cleaner#16]
Great Program but unfortunately if I set the "cleanup_movie_folders" to false everything works fine if I set it to true the following happens.
```
Cleaning up orphaned folders less than 30MB in Section 1
**[Flagged]: /media/Movies/Trading Places (1983)/
Size 2924304 bytes
**[Flagged]: /media/Movies/I Give It A Year (2013)/
Size 3025705 bytes
**[Flagged]: /media/Movies/Escape Plan (2013)/
Size 30211 bytes
**[Flagged]: /media/Movies/Primer (2004)/
Size 3 bytes
**[Flagged]: /media/Movies/Neighbors (2014)/
Size 2343609 bytes
**[Flagged]: /media/Movies/Rush (2013)/
Size 20593447 bytes
**[Flagged]: /media/Movies/Two Night Stand (2014)/
Size 2226141 bytes
**[Flagged]: /media/Movies/Nightcrawler (2014)/
Size 1086971 bytes
**[Flagged]: /media/Movies/Guest, The (2014)/
Size 1329303 bytes
Traceback (most recent call last):
  File "./PlexCleaner.py", line 943, in <module>
    changed = checkMovies(doc, Section)
  File "./PlexCleaner.py", line 609, in checkMovies
    cleanUpFolders(section, minimum_folder_size)
  File "./PlexCleaner.py", line 633, in cleanUpFolders
    size = getTotalSize(subfolder_path)
  File "./PlexCleaner.py", line 464, in getTotalSize
    total_size += getTotalSize(itempath)
  File "./PlexCleaner.py", line 460, in getTotalSize
    itempath = os.path.join(file, item)
  File "/usr/local/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
```

**Comment by ngovil21** [comment]
same advice as before, try running with python3. Python2 doesn't run as well with unicode.

**Comment by Dreded** [comment]
using python3 it worked and cleaned up the empty folders.... the name it was failing on previously was "Let's Be Cops"

**Comment by ngovil21** [comment]
Ya python2 encodes strings in a byte format that has problems with unicode characters. There are multiple types of apostrophes in unicode that mess up some of the older functions in python2. I tried formatting the strings, but it was too difficult to maintain compatibility for python2 and python3 and the same time.

Python3 handles string as unicode by default and is better for unicode strings.
