### ISSUE TITLE
Multi user configs in one file

### ISSUE THREAD

**Issue by snupple** [ngovil21/Plex-Cleaner#64]
I have 2 invited shared users that use my Plex and I have managed to get a separate config file that allows me to target those users and it seems to be working great.

My question is:  Can I amalgamate these users setting into one config file?

**Comment by ngovil21** [comment]
If it's working, probably best to keep it in two files.

You can specify multiple user tokens as a dict in the config file and then manage shows for each user using the `homeUsers` option.

To specify multiple tokens your token field would look like this:

```
Token: {
    "admin_user*": '[TOKEN_HERE],
    "second_user": '[TOKEN_2_HERE],
    ...
}
```
The admin user must have an `*` at the end as above and use lowercase for the names.

**Comment by snupple** [comment]
ah great, ok, so I created the above and I have a "Profile" that says that the admin user is a "homeUser"

When it runs, it will then say this:

```
INFO:root:[ERROR] Do not have the token for snupple. Please check spelling or token.
INFO:root:[INFO] snupple has not seen video 18954
INFO:root:[INFO] snupple has not seen video 18955
INFO:root:[INFO] snupple has not seen video 18956
INFO:root:[INFO] snupple has not seen video 18957
INFO:root:[INFO] snupple has not seen video 18959
INFO:root:[INFO] snupple has not seen video 18961
```

The interesting thing is, that for this profile there are two videos missing from the above and that is 18952 and 18953.   18953 is watched, 18952 and all the others are not watched.

It appears that it is seeing the token and tracking the views, but also at the same time saying it doesn't have the token?

I then changed the Profile in plex to be attached to a show that has only two episodes, both of which are watched:



```
Without  Profile  (min days 21):

INFO:root:9-1-1 - S01xE009 - Trapped | Viewed: 1 | Days Since Last Viewed: 18 | On Deck: False
INFO:root:[KEEPING] D:\Finished\TV\9-1-1\Season 1\9-1-1.-.S01E09.-.Trapped.HDTV-720p.mkv
INFO:root:
INFO:root:9-1-1 - S01xE010 - A Whole New You | Viewed: 1 | Days Since Last Viewed: 18 | On Deck: False
INFO:root:[KEEPING] D:\Finished\TV\9-1-1\Season 1\9-1-1.-.S01E10.-.A.Whole.New.You.HDTV-720p.mkv


With Profile (min days 21):

INFO:root:
INFO:root:[ERROR] Do not have the token for snupple. Please check spelling or token.
INFO:root:9-1-1 - S01xE009 - Trapped | Viewed: 0 | Days Since Last Viewed: 0 | On Deck: False
INFO:root:[KEEPING] D:\Finished\TV\9-1-1\Season 1\9-1-1.-.S01E09.-.Trapped.HDTV-720p.mkv
INFO:root:
INFO:root:9-1-1 - S01xE010 - A Whole New You | Viewed: 1 | Days Since Last Viewed: 18 | On Deck: False
INFO:root:[KEEPING] D:\Finished\TV\9-1-1\Season 1\9-1-1.-.S01E10.-.A.Whole.New.You.HDTV-720p.mkv
INFO:root:


With Profile (min days 7)  Set to FLAG:

INFO:root:
INFO:root:[ERROR] Do not have the token for snupple. Please check spelling or token.
INFO:root:9-1-1 - S01xE009 - Trapped | Viewed: 0 | Days Since Last Viewed: 0 | On Deck: False
INFO:root:[KEEPING] D:\Finished\TV\9-1-1\Season 1\9-1-1.-.S01E09.-.Trapped.HDTV-720p.mkv
INFO:root:
INFO:root:9-1-1 - S01xE010 - A Whole New You | Viewed: 1 | Days Since Last Viewed: 18 | On Deck: False
INFO:root:**[FLAGGED] D:\Finished\TV\9-1-1\Season 1\9-1-1.-.S01E10.-.A.Whole.New.You.HDTV-720p.mkv
INFO:root:

```

What I found is the runs "With Profile" not only say they can't find the token, but the first episode says the "Viewed" and "Days since Last Viewed" are both zero, however the first run without the profile attached has the correct values of 1 and 18.

Happy to fault-find more if you need it :)

**Comment by randybruder** [comment]
Do I have something wrong with my setup for multi-user tokens? Here's the snippet from my .conf file:

```
  "EmailRecipient": "", 
  "Token": {
    "randybruder*": '--------------ARNC1q',
    "katebruder": '--------------5ZbqWz'
  }
  "Username": "", 
```

I've tested the two tokens solo, so I know they both are valid and working. Here's the output from PlexCleaner.py:

```
Loading config file: /Applications/PlexCleaner/Cleaner_katie2.conf
Traceback (most recent call last):
  File "/Applications/PlexCleaner/PlexCleaner.py", line 1060, in <module>
    options = json.loads(opt_string)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
