### ISSUE TITLE
Local and remote mounting confusion

### ISSUE THREAD

**Issue by hippytyre** [ngovil21/Plex-Cleaner#85]
I run my plex server on an Nvidia Shield and I have a USB drive connected to a RaspberryPi which shares the files via samba to the plex server.

Currently when I run:
python ./PlexCleaner.py --test

I get a bunch of NOT FOUND results like this:

```
Hawaii Five-0 - S10xE017 - He kohu puahiohio i ka ho'olele i ka lepo i luna | Viewed: 1 | Days Since Last Viewed: 60 | On Deck: False
[NOT FOUND] /storage/DIETPI/Media Shares/Shows/Hawaii Five-0/Season 10/Hawaii Five-0 - S10E17 - He kohu puahiohio i ka ho'olele i ka lepo i luna SDTV.mkv
```

I know the problem is with local and remote mount but I don't know how to fix it.

```
 "RemoteMount": "",
 "LocalMount": "",
```

The correct path for the example would be:

`/mnt/USBHDD1/shares/Shows/Hawaii Five-0/Season 10/Hawaii Five-0 - S10E17 - He kohu puahiohio i ka ho'olele i ka lepo i luna SDTV.mkv`

How do I fix this problem?

Thanks

**Comment by hippytyre** [comment]
I'm getting a little closer to a solution I think.

  "RemoteMount": "/storage/DIETPI/Media Shares/",
  "LocalMount": "/mnt/USBHDD1/shares/",

This seems to sort out the paths but I get the following error after I run the script again with the --test flag.

Traceback (most recent call last):
  File "./PlexCleaner.py", line 1274, in <module>
    changed += checkShow(DirectoryNode)
  File "./PlexCleaner.py", line 955, in checkShow
    log('[KEEPING] ' + getLocalPath(ep['file']))
  File "./PlexCleaner.py", line 597, in getLocalPath
    if file.startswith(Settings['RemoteMount']):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 88: ordinal not in range(128)

``

**Comment by hippytyre** [comment]
I managed to fix the problem. 
python ./PlexCleaner.py --test --reload_encoding

Adding the --reload_encoding tag was the fix.


Hopefully someone else has this issue and my ramblings helped.
