### ISSUE TITLE
Issue with config file (new user)

### ISSUE THREAD

**Issue by tonyp1983** [ngovil21/Plex-Cleaner#86]
I'm trying to use this script for the first time and created a config file using --dump as per the instructions then updated it with my settings and preferences using nano. When I attempt to run the script, I get the following error:

`Loading config file: /mnt/Share/Configs/plexcleaner/cleaner.conf
Traceback (most recent call last):
  File "PlexCleaner.py", line 1063, in <module>
    options = json.loads(opt_string)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 1 column 1535 (char 1534)`

char 1534 of the .conf file appears to be ':' after  "MoviePreferences".

I didn't;t even edit that line, though I did edit the first profile in the section below to be the name of the collection I want to keep permanently (creatively called 'Keep', i.e.

`Profiles": {
    "Keep": {
      "action": "keep",
    }
`

**Comment by tonyp1983** [comment]
Not sure why but I was able to get this to work accidentally by running the script with an incorrect config file name, which caused the script to create a default config file that worked as expected when I updated with my details/options (despite them being the same as I had input previously)

**Comment by ngovil21** [comment]
ya the json doesn't do a good job of helping you debug but you can't have a comma in a set with nothinig after it. So setting your profile to `Profiles": { "Keep": { "action": "keep" }` should have worked

**Comment by tonyp1983** [comment]
Ah, that explains it. Didn’t even notice the comma, thanks for coming back to me, will keep an eye on that in future.
