### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 854 (char 853)

### ISSUE THREAD

**Issue by kingstonwa** [ngovil21/Plex-Cleaner#99]
Trying to run Plexcleaner.py --test on my Qnap and getting the following error below. Any help is appreciated

Loading config file: /share/CACHEDEV1_DATA/Plexcleaner/Cleaner.conf
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/Plexcleaner/PlexCleaner.py", line 1063, in <module>
    options = json.loads(opt_string)
  File "/opt/lib/python3.8/json/__init__.py", line 357, in loads
  File "/opt/lib/python3.8/json/decoder.py", line 337, in decode
  File "/opt/lib/python3.8/json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 854 (char 853)

**Comment by kingstonwa** [comment]
Fyi contacted Qnap support and they said it was my config file and sure enough I replaced with an older backup and now everything works
